SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_MIN_SIDES = 5
ASTEROID_MAX_SIDES = 15
ASTEROID_ROTATION_SPEED = 50  # degrees per second
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPEED_CHANGE = 2 # asteroid max speed change factor when splitting
ASTEROID_POINT_DENOMINATOR = 10

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds


SHOT_RADIUS = 5